import {renderSources,renderDelivery} from './delivery.js';
const bridge = window.AstrBotPluginPage;
const main = document.querySelector('#main');
const errorBox = document.querySelector('#error');
const loading = document.querySelector('#loading');
const lifetime = new AbortController();
let rendered = new AbortController();
let overview, features = [], diagnostics, sources, delivery, active = true, busy = false, generation = 0, offset = 0, deliveryOffset = 0;
const titles = {overview:'总览',connection:'连接',features:'功能目录',diagnostics:'诊断',sources:'来源与授权',delivery:'交付与覆盖'};
const states = {partial:'部分适配',verified_record:'历史证据已核对',effective:'有效',disabled:'意图关闭',not_implemented:'尚未实施',pending_verification:'待验证',unimplementable:'当前约束下无法实现',unknown:'未知',parent_disabled:'父级关闭',global_disabled:'全局禁止',permission_denied:'权限不足',mode_paused:'模式暂停',source_disabled:'来源关闭'};
const scopes = {plugin_global:'插件全局',source:'指定来源',core_instance:'Core 实例（影响其他宿主）',request:'请求级选择',object:'受控对象'};
function el(tag, text, className) {const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function listen(target,event,handler,signal=rendered.signal){target.addEventListener(event,handler,{signal});}
function view(){return titles[location.hash.slice(1)]?location.hash.slice(1):'overview';}
function card(title,text){const e=el('section',undefined,'card');e.append(el('h3',title),el('p',text));return e;}
function jsonDetails(title,value){const d=el('details');d.append(el('summary',title),el('pre',JSON.stringify(value,null,2)));return d;}
async function call(endpoint,body){if(!active)throw new Error('PAGE_CLOSED');return body===undefined?bridge.apiGet(endpoint):bridge.apiPost(endpoint,body);}
function errorMessage(error){const code=String(error?.message||'请求失败');return code.includes('REVISION_CONFLICT')?'设置已被另一页面修改。请刷新后重新编辑。':code.includes('REAUTHORIZE')?'Core 管理会话未授权或已过期，请重新提供合法会话。':'请求未完成，请刷新后核对状态。'+( /^[A-Z_ ]+$/.test(code)?' '+code:'');}
async function run(action){if(busy||!active)return;busy=true;errorBox.hidden=true;loading.textContent='处理中…';document.querySelector('#refresh').disabled=true;try{await action();if(active)loading.textContent='状态已更新';}catch(error){if(active){errorBox.textContent=errorMessage(error);errorBox.hidden=false;loading.textContent='请求未完成';}}finally{busy=false;if(active)document.querySelector('#refresh').disabled=false;}}
async function refresh(){if(!active)return;const current=++generation;const next=await call('overview');if(!active||current!==generation)return;const directory=await bridge.apiGet('features',{offset:0,limit:100});if(!active||current!==generation)return;if(directory.total>1000)throw new Error('CATALOG_LIMIT');for(let start=100;start<directory.total;start+=100){const page=await bridge.apiGet('features',{offset:start,limit:100});if(!active||current!==generation)return;directory.items.push(...page.items);}const diag=await bridge.apiGet('diagnostics',{offset,limit:50});if(!active||current!==generation)return;const sourceData=await call('sources');if(!active||current!==generation)return;const deliveryData=await bridge.apiGet('delivery',{offset:deliveryOffset});if(!active||current!==generation)return;sources=sourceData;delivery=deliveryData;overview=next;features=directory.items;diagnostics=diag;render();}
function observation(name){const o=overview.observations[name];return o?.current?o.value:null;}
function render(){if(!active||!overview)return;rendered.abort();rendered=new AbortController();main.replaceChildren();const tab=view();document.querySelectorAll('nav a').forEach(a=>{if(a.hash==='#'+tab)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});main.append(el('h2',titles[tab]));({overview:renderOverview,connection:renderConnection,features:renderFeatures,diagnostics:renderDiagnostics,sources:()=>renderSources({main,el,card,field,button,jsonDetails,listen,run,call,refresh,sources,overview,diagnostics}),delivery:()=>renderDelivery({main,el,card,button,jsonDetails,call,refresh,sources,delivery,diagnostics,deliveryPage:async(next)=>{deliveryOffset=next;await refresh();}})}[tab])();}
function renderOverview(){main.append(card('验证边界','历史本地宿主 Pages 已验证；Core 通信工程已验收。S2 业务接入资格尚待验收；连通性和管理读面成功不代表 READY 接入通过。远端构建与当前环境资格未知。'));const conn=observation('connection');const status=observation('status');const health=conn?.health||status;const grid=el('div',undefined,'grid');grid.append(card('插件生命周期',overview.lifecycle),card('Core 连接',conn?.connection||'未知／未检查'),card('Host 协议与权限',`${conn?.protocol||'未知'} / ${conn?.permission||'未知'}`),card('实例与模型许可',health?`业务就绪：${health.business_ready?'是':'否'}；模型许可：${health.model_dispatch}`:'未知；需手动只读检查'));main.append(grid);const local=card('本地产品控制','停止新采集及首次提交；未确认操作继续合法核对。');const toggle=el('input');toggle.type='checkbox';toggle.id='enabled';toggle.checked=overview.settings.intents['plugin.enabled'];const label=el('label','启用本地产品总闸');label.htmlFor='enabled';local.append(toggle,label);listen(toggle,'change',()=>run(async()=>{await call('controls/save',{expected_revision:overview.settings.revision,action_key:'plugin.enabled',desired:toggle.checked});await refresh();}));main.append(local);const limitations=card('明确限制','');const list=el('ul');overview.limits.forEach(x=>list.append(el('li',x)));limitations.append(list);main.append(limitations,jsonDetails('本地依赖基线（不是远端构建证明）',overview.local_baseline),jsonDetails('最近观测（标注时间与是否仍有效）',overview.observations));}
function field(form,id,title,type='text',value=''){const label=el('label',title);label.htmlFor=id;const input=el('input');input.id=id;input.name=id;input.type=type;input.value=value;input.autocomplete='off';form.append(label,input);return input;}
function button(parent,text,handler){const b=el('button',text);b.type='button';listen(b,'click',()=>run(handler));parent.append(b);return b;}
function renderConnection(){const config=overview.settings;const form=el('form');form.append(el('h3','Core 连接'),el('p',`控制版本 ${config.revision} · Host 凭据${config.credential_configured?'已配置':'未配置'}`));const address=field(form,'origin','Core HTTP(S) 根地址','url',config.origin);address.required=true;const token=field(form,'token','替换 Host Bearer（留空保留；换地址时清除）','password');token.maxLength=4096;const clear=el('input');clear.type='checkbox';clear.id='clear-token';const clearLabel=el('label','清除已保存 Host 凭据');clearLabel.htmlFor='clear-token';form.append(clearLabel,clear,el('p','凭据仅后端受限文件保存，未加密；不回显、不导出。','muted'));const submit=el('button','保存连接');submit.type='submit';form.append(submit);listen(form,'submit',event=>{event.preventDefault();const body={expected_revision:config.revision,origin:address.value};if(clear.checked)body.token='';else if(token.value)body.token=token.value;token.value='';run(async()=>{await call('connection/save',body);await refresh();});});button(form,'预览连接／凭据变更影响',async()=>{const value=await call('connection/impact',{});if(active)form.append(jsonDetails('影响预览',value));});button(form,'只读连接检查',async()=>{await call('connection/check',{});await refresh();});main.append(form);const latest=overview.observations.connection;if(latest){const result=latest.value;main.append(card('最近只读检查',`连接：${result.connection}；协议：${result.protocol}；权限：${result.permission}。${result.errors.length?'检查问题：'+result.errors.join('、'):'检查已完成'}${result.http_status!==undefined?'；HTTP '+result.http_status+'；结果 '+result.outcome+'；待清理：'+(result.cleanup_pending?'是':'否'):''}${latest.current?'':'（历史观测，需重新核实）'}`));}const admin=el('form');admin.append(el('h3','当前宿主用户的 Core 管理会话'),el('p','仅使用已合法取得的 Core 会话进行来源、令牌管理和必要只读查询；不自动登录、不保存管理员密码。授权最多保留十分钟，重启或连接变化后需重新授权。'));const session=field(admin,'session','iris_session 值','password');const csrf=field(admin,'csrf','iris_csrf 值','password');session.maxLength=csrf.maxLength=4096;const authorize=el('button','验证并暂存本用户会话');authorize.type='submit';admin.append(authorize);listen(admin,'submit',event=>{event.preventDefault();const body={session:session.value,csrf:csrf.value,expected_revision:config.revision};session.value=csrf.value='';run(async()=>{await call('admin/authorize',body);await refresh();});});button(admin,'只读管理状态',async()=>{await call('admin/status',{});await refresh();});button(admin,'清除本地管理授权',async()=>{await call('admin/revoke',{});await refresh();});main.append(admin,el('p','清除本地授权会关闭本插件会话，不代替在 Core 撤销该会话。','muted'));}
function renderFeatures(){main.append(el('p',`${features.length} 个独立控制／子能力；F01～F61 全部保留。未实施项无可执行按钮。`));const filters=el('div',undefined,'filters');const domainLabel=el('label','按功能域筛选');const select=el('select');select.setAttribute('aria-label','功能域');for(const domain of ['全部',...new Set(features.map(x=>x.domain))]){const option=el('option',domain);option.value=domain;select.append(option);}domainLabel.append(select);filters.append(domainLabel);main.append(filters);const results=el('div');main.append(results);let page=0;function draw(){results.replaceChildren();const chosen=features.filter(x=>select.value==='全部'||x.domain===select.value);const controls=el('div',undefined,'actions');const previous=el('button','前一页');previous.type='button';previous.disabled=page===0;previous.onclick=()=>{page--;draw();};const next=el('button','后一页');next.type='button';next.disabled=(page+1)*50>=chosen.length;next.onclick=()=>{page++;draw();};controls.append(previous,el('span',`${page*50+1}–${Math.min((page+1)*50,chosen.length)} / ${chosen.length}`),next);results.append(controls);const groups=Map.groupBy(chosen.slice(page*50,(page+1)*50),x=>x.feature_id);for(const [id,items] of groups){const group=el('section',undefined,'card');group.append(el('h3',id==='BASE'?'基础与通信控制':id));for(const item of items){const row=el('div',undefined,'action-row');row.append(el('strong',item.label),el('span',states[item.state]||item.state,'badge'),el('p',item.reason),el('small',`作用域：${scopes[item.scope]||item.scope} · 意图：${item.desired?'开':'关'} · 实际效果：${item.effective?'有效':'无'} · 版本 ${item.revision}`));row.append(jsonDetails('依赖与能力边界',{action_key:item.action_key,implemented:item.implemented,supported:item.supported,dependencies:item.dependencies,description:item.description,limitation:item.limitation_id||null,observed_at:item.observed_at}));group.append(row);}results.append(group);}}listen(select,'change',()=>{page=0;draw();});draw();}
function renderDiagnostics(){main.append(card('模型用量','AstrBot / Core：未接入／未知'),card('本地控制版本',String(diagnostics.revision)),jsonDetails('资源占用',diagnostics.resources),jsonDetails('脱敏错误（最多 100 条）',diagnostics.errors),jsonDetails('原操作（不含原输入、原 key 或凭据）',diagnostics.operations),el('p',diagnostics.credential_storage));const actions=el('div',undefined,'actions');const previous=button(actions,'上一页',async()=>{offset=Math.max(0,offset-50);await refresh();});previous.disabled=offset===0;const next=button(actions,'下一页',async()=>{offset+=50;await refresh();});next.disabled=offset+50>=diagnostics.operations.total;main.append(actions);}
listen(window,'hashchange',()=>{render();main.focus();},lifetime.signal);listen(document.querySelector('#refresh'),'click',()=>run(refresh),lifetime.signal);
listen(window,'pagehide',()=>{active=false;generation++;rendered.abort();lifetime.abort();document.querySelectorAll('input[type=password]').forEach(e=>{e.value='';});overview=undefined;features=[];diagnostics=undefined;},lifetime.signal);
// The public bridge has no HTTP cancellation API. Requests are finite, no polling,
// and late results are discarded after pagehide; the backend enforces deadlines.
if(!bridge){loading.textContent='请从 AstrBot 插件详情的 iris Page 打开';}else{try{await bridge.ready();if(active)await run(refresh);}catch{loading.textContent='宿主 bridge 未就绪，请刷新页面';}}
