const $ = (s, root = document) => root.querySelector(s);
const el = (tag, attrs = {}, text = '') => { const n = document.createElement(tag); for (const [k,v] of Object.entries(attrs)) n.setAttribute(k,v); n.textContent = text; return n; };
const view = $('#view');
let status, currentView = 'overview', currentPersona, personas = [], bridge, lastLogs = [];
const titles = {overview:'概览',settings:'配置管理',modules:'功能模块',personas:'人格',memory:'记忆',tasks:'主动与提醒',logs:'运行日志'};
function notice(text, error=false) { const n=$('#notice'); n.hidden=!text; n.textContent=text; n.className=error?'error':''; }
async function api(action, data={}) { const result=await bridge.apiPost('v4/query',{action,data}); if(result.status!=='ok') throw new Error(result.message||'操作失败'); return result.data; }
async function guard(fn, button) { if(button)button.disabled=true; try {return await fn();} catch(e){notice(e.message||String(e),true);} finally{if(button)button.disabled=false;} }
function button(text, fn, cls='') {const b=el('button',{type:'button',class:cls},text); b.onclick=()=>guard(()=>fn(b),b);return b;}
function field(label, kind='text', value='') {const wrap=el('label'), name=el('span',{},label);let input=kind==='textarea'?el('textarea'):kind==='select'?el('select'):el('input',{type:kind});if(kind==='checkbox')input.checked=!!value;else input.value=value;wrap.append(name,input);return [wrap,input];}
function panel(title){const n=el('section',{class:'panel'});if(title)n.append(el('h2',{},title));return n;}
function output(value, root=view){const p=el('pre',{class:'result'},JSON.stringify(value,null,2));root.append(p);return p;}
function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=el('a',{href:url,download:name});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function refresh(){status=await api('status');$('#mode').textContent=(status.mode==='local'?'本地 Core':'远程 Core')+' · r'+status.revision;await render(currentView);}
async function render(name){currentView=name;$('#title').textContent=titles[name];document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));view.replaceChildren();await ({overview,settings,modules,personas:personaPage,memory,tasks,logs})[name]();}
function overview(){
 const hero=el('div',{class:'hero'});hero.append(el('div',{class:'eyebrow'},'A LITTLE MEMORY, A LITTLE CLOSER'),el('h2',{},'从记住，到更好的陪伴。'),el('p',{},'在这里管理 Iris 的记忆、人格与主动提醒。功能按需开启，模型调用共用预算。'));view.append(hero);
 const grid=el('div',{class:'grid'});for(const [label,value,hint] of [['运行中的模块',Object.values(status.modules).filter(x=>x.state==='running').length+' / '+Object.keys(status.modules).length,'未启用的功能不启动后台任务'],['已启用会话',status.settings.allowed_conversations.length,'在目标会话执行 /iris status 获取会话键'],['每日模型调用上限',status.settings.daily_model_calls,'不包含 AstrBot 自身的被动回复']]){const c=el('article',{class:'card'});c.append(el('div',{class:'muted'},label),el('div',{class:'metric'},String(value)),el('p',{class:'hint'},hint));grid.append(c);}view.append(grid);
 const p=panel('开始使用');p.style.marginTop='24px';p.append(el('p',{class:'muted'},'先安装对应 Core / SDK 依赖，再选择会话和模块。完整人格可以独立编辑与发布。'),button('配置 Iris',()=>render('settings')),el('p',{class:'check-note'},'开发候选版本：本地 Core 使用 Unix 目录锁，SQLite 需符合 Core 支持范围。远程会话与人格需由服务端预配置 Agent / Space。自动记忆提炼暂受 Core 认知桥接作用域缺口限制。'));view.append(p);
 const failed=Object.entries(status.modules).filter(([,v])=>v.error);if(failed.length)output(failed,p);
}
async function settings(){
 const form=el('form');form.onsubmit=e=>e.preventDefault();const inputs=new Map(),groups=new Map();let providers={chat:[],embedding:[]};try{providers=await api('providers');}catch{notice('无法读取模型列表，仍可手动填写 Provider ID',true);}
 for(const f of status.fields){if(!groups.has(f.group)){const p=panel(f.group),g=el('div',{class:'fields'});p.append(g);form.append(p);groups.set(f.group,g);}const kind=['object','list'].includes(f.kind)?'textarea':f.kind==='boolean'?'checkbox':['number','integer'].includes(f.kind)?'number':f.secret?'password':'text';const [wrap,input]=field(f.label,kind,kind==='textarea'?JSON.stringify(status.settings[f.key],null,2):status.settings[f.key]);input.name=f.key;if(f.minimum!==null)input.min=f.minimum;if(f.maximum!==null)input.max=f.maximum;if(kind==='number')input.step=f.kind==='integer'?'1':'any';if(kind==='checkbox')wrap.classList.add('checkbox-row');if(kind==='textarea')wrap.classList.add('wide');
 if(f.secret){input.autocomplete='new-password';input.placeholder=status.settings[f.key+'_configured']?'已配置；留空保留':'未配置';const clear=field('清除已保存的 Token','checkbox');wrap.append(clear[0]);input.clearInput=clear[1];}
 if(f.key.endsWith('_provider')){const id='providers-'+f.key;input.setAttribute('list',id);const list=el('datalist',{id});for(const p of (f.key==='embedding_provider'?providers.embedding:providers.chat)){list.append(el('option',{value:p.id},p.model));}wrap.append(list);}
 wrap.append(el('small',{class:'hint'},f.hint||''));groups.get(f.group).append(wrap);inputs.set(f.key,{f,input});}
 const actions=el('div',{class:'sticky-actions'});actions.append(button('保存并应用',async()=>{const changes={};for(const [key,{f,input}] of inputs){let value;if(f.secret&& !input.value && !input.clearInput.checked)continue;if(f.kind==='boolean')value=input.checked;else if(['object','list'].includes(f.kind))value=JSON.parse(input.value);else if(['number','integer'].includes(f.kind))value=Number(input.value);else value=input.value;if(JSON.stringify(value)!==JSON.stringify(status.settings[key])||f.secret)changes[key]=value;}await api('config.validate',{changes});status=await api('config.apply',{changes,expected_revision:status.revision});notice('配置已应用，相关模块已完成重载');await refresh();}),el('span',{class:'muted'},'Core 模式在 AstrBot 插件配置中选择，切换不迁移数据。'));form.append(actions);view.append(form);
}
function modules(){const g=el('div',{class:'grid'}),checks={};for(const [id,m] of Object.entries(status.modules)){const p=el('article',{class:'card'}),top=el('div',{class:'module-head'});const [wrap,input]=field(m.label,'checkbox',m.enabled);input.setAttribute('aria-label',m.label);wrap.className='checkbox-row';checks[id]=input;top.append(wrap,el('span',{class:'badge '+m.state},{running:'运行中',disabled:'未开启',failed:'启动失败'}[m.state]));p.append(top,el('p',{class:'module-detail'},m.dependencies.length?'依赖：'+m.dependencies.map(x=>status.modules[x].label).join('、'):'可以独立启用'));if(m.error)p.append(el('p',{class:'hint'},m.error.code+' · '+m.error.message));g.append(p);}view.append(g);const a=el('div',{class:'sticky-actions'});a.style.marginTop='22px';a.append(button('应用模块开关',async()=>{const modules=Object.fromEntries(Object.entries(checks).map(([k,v])=>[k,v.checked]));status=await api('config.apply',{changes:{modules},expected_revision:status.revision});notice('模块状态已更新');await refresh();}),el('span',{class:'muted'},'请同时开启依赖；关闭时请同时关闭依赖此模块的功能。'));view.append(a);}
async function personaPage(){personas=await api('personas');if(currentPersona)currentPersona=personas.find(p=>p.key===currentPersona.key);const top=el('div',{class:'section-top'});top.append(el('p',{class:'muted'},'编辑为草稿，发布后在下一次对话采用。回滚会新增修订。'),button('新建人格',()=>{currentPersona=null;return render('personas');}));view.append(top);const split=el('div',{class:'split'}),list=el('div',{class:'persona-list'}),editor=panel(currentPersona?'编辑人格':'新建人格');for(const p of personas){const b=button(p.value.name,()=>{currentPersona=p;return render('personas');},currentPersona?.key===p.key?'selected':'');b.append(el('small',{},p.value.disabled?'已停用':p.value.published?'已发布 r'+p.value.published.revision:'未发布'));list.append(b);}split.append(list,editor);view.append(split);
 const [nw,ni]=field('名称','text',currentPersona?.value.name||''),[tw,ti]=field('完整人格正文','textarea',currentPersona?.value.text||'');ti.className='persona-text';editor.append(nw,tw);const a=el('div',{class:'actions'});a.style.marginTop='18px';a.append(button('保存草稿',async()=>{const r=await api('persona.save',{persona_id:currentPersona?.key,name:ni.value,text:ti.value,expected_revision:currentPersona?.revision||0});currentPersona={key:r.value.id,...r};notice('草稿已保存');await render('personas');}));
 if(currentPersona){const base={persona_id:currentPersona.key,expected_revision:currentPersona.revision};a.append(button('发布已保存修订',async()=>{await api('persona.publish',base);notice('已发布；下一次对话将采用新修订');await render('personas');},'secondary'),button('导出',async()=>download(await api('persona.export',base),'iris-persona.json'),'secondary'),button('停用',async()=>{await api('persona.disable',base);notice('人格已停用');await render('personas');},'danger'));const history=el('details');history.append(el('summary',{},'修订历史与回滚'));history.ontoggle=()=>{if(history.open&&!history.loaded){history.loaded=true;guard(async()=>{for(const r of await api('persona.history',base)){const row=el('div',{class:'memory-item'});row.append(el('span',{},'r'+r.revision+' · '+r.value.reason+' '),button('回滚到此修订',async()=>{await api('persona.rollback',{...base,target_revision:r.revision});notice('已回滚并发布新修订');await render('personas');},'secondary'));history.append(row);}});}};editor.append(history);}
 editor.append(a);
 const p=panel('绑定与导入');const [cw,ci]=field('会话键 / 会话绑定键','text'),[pw,pi]=field('人格','select');pi.append(el('option',{value:''},'解除绑定'));for(const p of personas.filter(x=>x.value.published&&!x.value.disabled))pi.append(el('option',{value:p.key},p.value.name));p.append(cw,pw,button('保存绑定',async()=>{const all=await api('bindings'),existing=all.find(x=>x.key===ci.value);await api('persona.bind',{key:ci.value,persona_id:pi.value,expected_revision:existing?.revision||0});notice('绑定已保存');}));const [iw,ii]=field('导入人格 JSON','file');ii.accept='.json,application/json';ii.onchange=()=>guard(async()=>{const f=ii.files[0];if(!f)return;if(f.size>262144)throw new Error('文件超过 256 KiB');await api('persona.import',{document:JSON.parse(await f.text())});notice('已导入为新草稿');await render('personas');});p.append(iw);view.append(p);
 if(currentPersona?.value.published){const learning=panel('从记忆起草人格修订'),conversation=await conversationSelect(learning),[qw,qi]=field('需要参考的主题');learning.append(qw,button('生成草稿',async()=>{const r=await api('learning.draft',{conversation:conversation.value,persona_id:currentPersona.key,query:qi.value,expected_revision:currentPersona.revision});currentPersona={key:r.value.id,...r};notice('学习草稿已保存，尚未发布');await render('personas');}),el('p',{class:'hint'},'需启用人格学习并选择模型。只使用当前有效的 Claim 作为证据，发布前会再次验证。'));view.append(learning);}
}
async function conversationSelect(root){const [wrap,input]=field('目标会话','select');input.append(el('option',{value:''},'请选择已登记的会话'));for(const c of await api('conversations'))input.append(el('option',{value:c.key},c.value.display_name+' · '+c.key));root.append(wrap);return input;}
async function memory(){const p=panel('查找与管理记忆');const conversation=await conversationSelect(p),[qw,qi]=field('查询主题','text');p.append(qw);const results=el('div');p.append(button('召回记忆',async()=>{const r=await api('memory.recall',{conversation:conversation.value,query:qi.value});results.replaceChildren();results.append(el('p',{class:'hint'},'候选 '+r.candidates.length+' 条 · '+(r.partial?'部分路由降级':'召回完成')));for(const c of r.candidates){const item=el('article',{class:'memory-item'}),ref=c.resource_ref;item.append(el('small',{},ref.resource_type+' · '+ref.resource_id+' · r'+ref.revision),el('p',{},c.text));if(ref.resource_type==='claim'){const actions=el('div',{class:'actions'});actions.append(button('纠正',async()=>{const [w,i]=field('纠正后的事实','textarea',c.text);item.append(w,button('保存纠正',async()=>{await api('memory.correct',{conversation:conversation.value,claim_id:ref.resource_id,text:i.value,expected_revision:ref.revision,idempotency_key:crypto.randomUUID()});notice('记忆已纠正，请重新召回');}));},'secondary'),button('遗忘此条事实',async()=>{await api('memory.forget',{conversation:conversation.value,claim_id:ref.resource_id,idempotency_key:crypto.randomUUID()});item.remove();notice('已删除此条 Claim；原始对话观察不随 Claim 删除。');},'danger'));item.append(actions);}results.append(item);}const details=el('details');details.append(el('summary',{},'查看召回诊断'));output(r,details);results.append(details);}));p.append(button("查看用户画像",async()=>output(await api("memory.profile",{conversation:conversation.value}),results),"secondary"),results);view.append(p);
 const w=panel('明确记住');const [tw,ti]=field('用户明确提供的事实','textarea');w.append(tw,button('保存记忆',async()=>{await api('memory.remember',{conversation:conversation.value,text:ti.value,idempotency_key:crypto.randomUUID()});notice('记忆已保存到 Core');ti.value='';}));view.append(w);
 const maintenance=panel('索引维护');maintenance.append(el('p',{class:'hint'},'需先开启后台维护模块。重建只提交 Core 作业，不在插件复制索引。'));const [kw,ki]=field('索引类型','select');for(const k of ['fts','graph','profile','vector','recent_context'])ki.append(el('option',{value:k},k));maintenance.append(kw,button('提交重建',async()=>output(await api('maintenance.rebuild',{kind:ki.value}),maintenance),'secondary'),button('运行一个维护批次',async()=>output(await api('maintenance.run'),maintenance),'secondary'));view.append(maintenance);
}
async function tasks(){const p=panel('提醒');const conversation=await conversationSelect(p),[tw,ti]=field('提醒内容'),[dw,di]=field('提醒时间（浏览器本地时区）','datetime-local');p.append(tw,dw,button('创建提醒',async()=>{const date=new Date(di.value);if(!Number.isFinite(date.getTime()))throw new Error('请选择有效时间');await api('task.create',{conversation:conversation.value,title:ti.value,due_at_us:date.getTime()*1000,idempotency_key:crypto.randomUUID()});notice('提醒已创建；启用主动模块后执行');}));const list=el('div');p.append(button('查看任务',async()=>{const r=await api('task.list',{conversation:conversation.value});list.replaceChildren();for(const t of r.items||[]){const row=el('article',{class:'memory-item'});row.append(el('h3',{},t.title),el('small',{},t.status+' · '+(t.due_at_us?new Date(t.due_at_us/1000).toLocaleString():'无截止时间')));for(const [label,target] of [['激活','activate'],['完成','complete'],['取消','cancel']])row.append(button(label,async()=>{await api('task.transition',{conversation:conversation.value,task_id:t.task_id,target,expected_revision:t.revision,idempotency_key:crypto.randomUUID()});notice('任务状态已更新，请刷新列表');},'secondary'));list.append(row);}},'secondary'),list);view.append(p);const d=panel('交付状态');d.append(el('p',{class:'muted'},'发送结果未知时不会自动重发。平台接收不等同于用户送达；提醒发送也不自动完成原任务。'),button('查看队列与发送回执',async()=>output(await api('delivery.status'),d),'secondary'));view.append(d);await focusPanel(conversation);}
async function focusPanel(conversation){
 const p=panel('关注点'),[w,i]=field('需要持续关注的事情','textarea'),list=el('div');p.append(w,button('记录关注点',async()=>{await api('task.focus.create',{conversation:conversation.value,summary:i.value,idempotency_key:crypto.randomUUID()});notice('关注点已存入 Core，会参与统一召回');}),button('查看关注点',async()=>{const r=await api('task.focus.list',{conversation:conversation.value});list.replaceChildren();for(const f of r.items||[]){const row=el('article',{class:'memory-item'});row.append(el('p',{},f.summary),button('结束关注',async()=>{await api('task.focus.dismiss',{conversation:conversation.value,focus_item_id:f.focus_item_id,expected_revision:f.revision,idempotency_key:crypto.randomUUID()});row.remove();},'secondary'));list.append(row);}},'secondary'),list);view.append(p);
}
async function logs(){const p=panel('运行记录'),[lw,li]=field('级别','select'),[ow,oi]=field('操作名称筛选');for(const l of ['','DEBUG','INFO','WARNING','ERROR'])li.append(el('option',{value:l},l||'全部'));const f=el('div',{class:'fields'});f.append(lw,ow);p.append(f);const list=el('div');p.append(button('查询日志',async()=>{const r=await api('logs',{level:li.value,operation:oi.value,limit:100});lastLogs=r.records;list.replaceChildren();list.append(el('p',{class:'hint'},'本次 '+r.records.length+' 条 · 缓冲丢弃 '+r.dropped+' 条'));for(const row of r.records){const d=el('details',{class:'log-entry'}),s=el('summary');s.append(el('span',{class:'log-time'},new Date(row.time*1000).toLocaleTimeString()),el('span',{},row.level),el('span',{},row.operation));d.append(s,el('pre',{},JSON.stringify(row,null,2)));list.append(d);}}),button('导出查询结果',()=>download(lastLogs,'iris-logs.json'),'secondary'),el('p',{class:'hint'},'完整日志在“功能模块”开启。默认只保留 AstrBot 基础错误日志；详细正文需单独开启。'),list);view.append(p);}
for(const b of document.querySelectorAll('nav button'))b.onclick=()=>guard(()=>render(b.dataset.view));$('#refresh').onclick=()=>guard(refresh,$('#refresh'));
try{bridge=window.AstrBotPluginPage;if(!bridge)throw new Error('请从 AstrBot 的插件 Pages 打开此页面。');await bridge.ready();await refresh();}catch(e){notice(e.message,true);view.replaceChildren(el('p',{class:'empty'},'连接尚未建立。请确认插件已加载，然后点击刷新。'));}
